[project]
name = "fiap-eml-tech-challenger-fase-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.119.0",
    "psycopg2>=2.9.11",
    "psycopg2-binary>=2.9.11",
    "uvicorn>=0.37.0",
]
